### ISSUE TITLE
Cannot find maven dependency

### ISSUE THREAD

**Issue by ajschwieterman** [truongsinh/appium-flutter-driver#101]
I am using the following dependency to import the finder methods in the Appium Flutter driver, but my IDE cannot find them.

`
<dependency>
<groupId>pro.truongsinh</groupId>
<artifactId>appium-flutter-finder</artifactId>
<version>0.0.4</version>
</dependency>
`

**Comment by sahanaprasad** [comment]
i'm facing the same issue. Any update?

**Comment by ahashmi24** [comment]
@sahanaprasad 
you can get appium-flutter-finder dependency from [here](https://github.com/truongsinh/appium-flutter-driver/files/3541350/repository.zip) and keep it in your local machine and passed its path in pom.xml 

pom.xml snippet:
                 <repository>
			<id>local-maven-repo</id>
			<url>file:///lib/repository</url>
		</repository>

I recommend you to keep dependency (pro folder) in m2 repository after downloading from above link.

**Comment by sahanaprasad** [comment]
can you please send me the code snippet.
@ahashmi24

**Comment by ajschwieterman** [comment]
@sahanaprasad I downloaded the files into my .m2 repo without changing the pom.xml file to reference this dependency.

**Comment by baselalali** [comment]
Any update? I facing the same issue

**Comment by baselalali** [comment]
have any person problem with getText(), isDisplayed

```
   <dependencies>
        <!-- FLUTTER FINDER -->
        <dependency>
            <groupId>io.github.ashwithpoojary98</groupId>
            <artifactId>appium_flutterfinder_java</artifactId>
            <version>1.0.1</version>
        </dependency> 
```
