### ISSUE TITLE
 "ext.flutter.driver" is not found in "extensionRPCs"

### ISSUE THREAD

**Issue by sahanaprasad** [truongsinh/appium-flutter-driver#102]
I have been trying to automate flutter application with Appium flutter driver.
Getting the following issue. (Appium log). Kindly help me with this. Thanks in advance.
capabilities:
const wdio = require('webdriverio');
const assert = require('assert');
const find = require('appium-flutter-finder');

const osSpecificOps =
  process.env.APPIUM_OS === 'android'
    ? {
        platformName: 'Android',
        deviceName: 'emulator-5554',
       
       app: '/Users/<username>/Documents/appium-flutter-driver/aut/app-debug.apk'
      }
    : process.env.APPIUM_OS === 'ios'
    ? {
        platformName: 'iOS',
        platformVersion: '12.2',
        deviceName: 'iPhone X',
        noReset: true,
        
         app: '/Users/<username>/Documents/appium-flutter-driver/aut/app-debug.apk'
      }
    : {};

const opts = {
  port: 4723,
  capabilities: {
    ...osSpecificOps,
    automationName: 'Flutter'
  }
};

main.dart file
import 'package:flutter/material.dart';
import 'package:flutter_driver/driver_extension.dart';

void main() {
  enableFlutterDriverExtension();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My FLutter Application',

      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MyStatefulWidgetState();

}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text("My Journal"),
      ),
      body: Center(

        child: Text('you have pressed the button $_count times.'),
         key: Key('counter'),
      ),
      backgroundColor: Colors.blueGrey.shade200,
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(()=> _count++),
        tooltip: 'Increment Counter',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

[appium log.pdf](https://github.com/truongsinh/appium-flutter-driver/files/5303532/appium.log.pdf)

**Comment by Reppinger** [comment]
@sahanaprasad there is an extensive discussion of this error in  #28

**Comment by sahanaprasad** [comment]
This issue only persists when running the suite on emulator. It works fine with the real device.
