### ISSUE TITLE
Annotations for finding UI elements

### ISSUE THREAD

**Issue by ajschwieterman** [truongsinh/appium-flutter-driver#108]
In the native drivers, annotations can be added to a MobileElement variable in replacement of using the traditional `driver.findElementById()` method.  Having these annotations for Flutter finder methods, like valueKey, would be very valuable.

<img width="653" alt="Screen Shot 2020-10-20 at 15 25 23" src="https://user-images.githubusercontent.com/50152740/96634588-bb5bcb80-12e8-11eb-9f94-93d17f6a755f.png">

**Comment by shibupanda** [comment]
@ajschwieterman Could you please create a proposal in testNg community.

**Comment by ajschwieterman** [comment]
@shibupanda Can you point me to where I can find the testNg community?

**Comment by shibupanda** [comment]
@ajschwieterman raise a proposal [here](https://github.com/cbeust/testng/issues).

**Comment by krmahadevan** [comment]
@shibupanda - Can you please help me understand as to how this would be connected to TestNG ?
