### ISSUE TITLE
Need an Application to test recently added action

### ISSUE THREAD

**Issue by shibupanda** [truongsinh/appium-flutter-driver#11]
@truongsinh 
Do we have any application where we can test recently added features like scroll, enterText and all?
One more question I have. suppose I don't have app source code or if I am concentrating only black-box testing then is there any way to retrieve locators like "byValueKey('increment')" etc. So that we can start implementing those in Appium desktop. 

Thanks.

**Comment by shibupanda** [comment]
@truongsinh 
I got my answer through below link.
https://flutter.dev/docs/development/tools/devtools/inspector

**Comment by truongsinh** [comment]
> Do we have any application where we can test recently added features like scroll, enterText and all?

Yes, I will update shortly

**Comment by truongsinh** [comment]
The application is now available at https://github.com/truongsinh/appium-flutter-driver/tree/master/example/flutter_app_under_test
