### ISSUE TITLE
FlutterDriver command timeout seems infinite

### ISSUE THREAD

**Issue by ajschwieterman** [truongsinh/appium-flutter-driver#114]
When I execute a FlutterDriver command using a FlutterElement that is either not displayed on the phone or not on the phone, the driver does not timeout; it stays stuck in an infinite loop.  I'm not aware of any timeouts I can set to solve this problem.  I set the implicit wait time using the following code:
```
driver.manage().timeouts().implicitlyWait(seconds, TimeUnit.SECONDS);
```

**Comment by baovu2512** [comment]
i've change the waitFor method to return element you search with timeout, you can check it out here https://github.com/truongsinh/appium-flutter-driver/pull/111.

**Comment by ajschwieterman** [comment]
Thank you @baovu2512!

**Comment by rahulacko** [comment]
This is not working. I am using appium flutter driver + Java. It just keeps on looking for the object to infinity. Do we have any solution for this?

**Comment by rahulacko** [comment]
```
[HTTP] {"id":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidG9tb3Jyb3dfY2hlY2tvdXQifQ"}
[debug] [MJSONWP (a1b6f0ac)] Calling AppiumDriver.click() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidG9tb3Jyb3dfY2hlY2tvdXQifQ","a1b6f0ac-da36-4178-a44d-fc9d0f1db854"]
[debug] [FlutterDriver] Executing Flutter driver command 'click'
[debug] [FlutterDriver] >>> {"command":"tap","finderType":"ByValueKey","keyValueType":"String","keyValueString":"tomorrow_checkout"}
```

Waiting here for more than an hour

**Comment by ajschwieterman** [comment]
What version of the `appium-flutter-driver` are you using?  v0.0.28 should not have this issue.

**Comment by rahulacko** [comment]
How to find the appium-flutter-driver version? @ajschwieterman

**Comment by ajschwieterman** [comment]
`npm -v appium-flutter-driver`

https://www.npmjs.com/package/appium-flutter-driver

**Comment by rahulacko** [comment]
@ajschwieterman it is 7.15.1

**Comment by ajschwieterman** [comment]
My mistake.  `npm view appium-flutter-driver version`

**Comment by rahulacko** [comment]
it is 0.0.28 @ajschwieterman

**Comment by ajschwieterman** [comment]
`(MobileElement) driver.executeScript("flutter:waitFor", find.byValueKey(locator), 30);`

**Comment by rahulacko** [comment]
it is still stuck in the same place. I don't see there is any timeout in the below scenarios-
1) When the script doesn't have the key but the mobile app screen has the object
2) When the script has the key but the same key is not present on the mobile screen.
@ajschwieterman

**Comment by rahulacko** [comment]
This is the error i m getting but it is not stopping my test cases. Keeps on searching

`Encountered internal error running command: Error: Cannot execute command waitFor, server reponse {
[debug] [MJSONWP (d79ca18a)]   "isError": true,
[debug] [MJSONWP (d79ca18a)]   "response": "Timeout while executing waitFor: TimeoutException after 0:00:10.000000: Future not completed\n",
[debug] [MJSONWP (d79ca18a)]   "type": "_extensionType",
[debug] [MJSONWP (d79ca18a)]   "method": "ext.flutter.driver"
[debug] [MJSONWP (d79ca18a)] }
[debug] [MJSONWP (d79ca18a)]     at FlutterDriver.exports.executeElementCommand (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:134:11)
[debug] [MJSONWP (d79ca18a)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [MJSONWP (d79ca18a)]     at Object.waitFor (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:3)`

**Comment by ajschwieterman** [comment]
Maybe ask @baovu2512 about the problems your seeing since he made the PR for this.

**Comment by rahulacko** [comment]
@baovu2512 can u please help here

**Comment by yanivamram** [comment]
Hey,
I am also facing this issue, lately more often the before.
When I have encountered with the issue for the first time, 
it suddenly vanished after I have tried to restart everything(appium server, wipe the emulator and cold boot etc.)

Yet, I could not find out what is the root cause, and now it happened again
Makes me nuts :-(

**Comment by rahulacko** [comment]
it is very irritating now. IF the element is not visible it keeps on waiting for infinite. Using the below line. It should timeout in 20 seconds but keeps on stuck at the same place

public MobileElement waitFor(String locator) {
        return (MobileElement) driver.executeScript("flutter:waitFor", find.byValueKey(locator), 20);
    }

**Comment by baovu2512** [comment]
Hi guys, sorry because so busy recently and cannot reply,. You guys can ping me via Skype : baovu2512. Support with screen sharing is easier.

**Comment by ravireddy07** [comment]
I'm also having same issue.... Where exactly i need to implement this wait..?
In capabilities..?
@rahulacko @baovu2512 @yanivamram

**Comment by narasimhanukala** [comment]
any updates on this?
i too experience that, when element is not on mobile screen, appium waits for infinite time..

**Comment by yanivamram** [comment]
@ravireddy07 
Sorry for the late response
On my case, it seems like the problem was a Flutter futures that didn't complete
For example, if you have an animation that never ends or alike, the appium-flutter-driver won't be able to find the element,
while on the appium server log you will see the response which include "future not completed"

Hope that could be helpful on your case
