### ISSUE TITLE
Process finished with exit code 254

### ISSUE THREAD

**Issue by Satyakunisetty** [truongsinh/appium-flutter-driver#121]
lib/main.dart: Warning: Interpreting this as package URI, 'package:hello_world/main.dart'.
../../../../Flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart:2121:39: Warning: Operand of null-aware operation '!' has type 'List<SemanticsNode>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'SemanticsNode' is from 'package:flutter/src/semantics/semantics.dart' ('../../../../Flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart').
    for (int position = 0; position < childrenInDefaultOrder!.length; position += 1) {
                                      ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/animated_icons.dart:11:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/animated_icons.dart:12:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/app.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/app_bar_theme.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/arc.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/bottom_navigation_bar_theme.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/bottom_sheet.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../../Flutter/flutter/packages/flutter/lib/src/material/button_bar_theme.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^

Process finished with exit code 254

Need help in resolving it

**Comment by Satyakunisetty** [comment]
Am i doing something wrong while executing this

**Comment by veerakunisetty** [comment]
I ave sorted out the above issue. so closing the issue

**Comment by shibupanda** [comment]
Closing as it's not related to driver. Please check the setup.
