### ISSUE TITLE
Does the appium-flutter driver work on real IOS devices as of now?

### ISSUE THREAD

**Issue by ArchitWagle** [truongsinh/appium-flutter-driver#123]
I see some issues here where people are using this appium-flutter driver with real IOS devices, but the readMe lists that real IOS devices is still a todo.

**Comment by ajschwieterman** [comment]
@ArchitWagle, yes, but it needs to be modified.

https://github.com/truongsinh/appium-flutter-driver/issues/39

**Comment by tevaAutomation** [comment]
Hi,
@ajschwieterman - do you know when will Appium-Flutter-Driver going to support in iOS real device? and will it support in iOS version 14 and above?

**Comment by ajschwieterman** [comment]
@tevaAutomation, I am not sure when the repo will be updated.  This is a better question for @truongsinh and @shibupanda as they are the owners of the repo.

**Comment by hex0cter** [comment]
@truongsinh @shibupanda Any plans to bump the version of appium-flutter-driver, to include https://github.com/truongsinh/appium-flutter-driver/pull/62, which is suppose to solve the problem of real iOS?

**Comment by shibupanda** [comment]
@hex0cter today I will publish it.
