### ISSUE TITLE
The commands are failing like flutter:getCenter, "flutter:checkHealth" etc.

### ISSUE THREAD

**Issue by shibupanda** [truongsinh/appium-flutter-driver#14]
@truongsinh 
The commands start failing like flutter:getCenter, "flutter:checkHealth" etc. 
Could you please check the below logs. 
Tested with latest and 0.0.16 flutter-driver and 0.0.13 flutter-finder 

Appium Logs:
https://gist.github.com/shibupanda/28328d9a389fb3a3639392f534b63037
WDIO Logs:
https://gist.github.com/shibupanda/6ecef6554f5b437a8101f4cdfd2f33c4

**Comment by truongsinh** [comment]
Do you use your own app or the example app? What is your Flutter version?

**Comment by shibupanda** [comment]
I am using the example app only.
Flutter version or appium-Flutter-driver version ?
Because previously I don't have flutter installed in my local machine.

**Comment by shibupanda** [comment]
I added flutter path in environment variable and commands are start working now.
But please don't close this thread as I am doing overall testing on this build. 
Appreciate your help. Thanks

**Comment by shibupanda** [comment]
@truongsinh closing this issue as I fixed all and now all the steps are working perfectly.

**Comment by truongsinh** [comment]
@shibupanda can you describe what steps to you do to fix?

**Comment by nknezevicpr** [comment]
> I added flutter path in environment variable and commands are start working now.
> But please don't close this thread as I am doing overall testing on this build.
> Appreciate your help. Thanks

@shibupanda Can you please sent me a PM or mail, I have couple questions for you?

**Comment by shibupanda** [comment]
Sure @truongsinh I will do that.
Sure @nknezevicpr I have sent.

Thank You.
