### ISSUE TITLE
waitFor seems to be not working for other than valueKey locator.

### ISSUE THREAD

**Issue by Prasea1993** [truongsinh/appium-flutter-driver#141]
When i tried to use waitFor condition with different flutterelements i.e. toolTip, text ,valueKey and Type. waitFor only working with valueKey as identifier.

Below code returning null pointer .
public MobileElement waitBasedOnType(String flutterElementType, String locatorValue, int waitTime) {
		MobileElement element = null;

		if (flutterElementType.equalsIgnoreCase("ToolTip")) {
			element = (MobileElement) driver.executeScript("flutter:waitFor", find.byTooltip(locatorValue), waitTime);
		} else if (flutterElementType.equalsIgnoreCase("Type")) {
			element = (MobileElement) driver.executeScript("flutter:waitFor", find.byType(locatorValue), waitTime);
		} else if (flutterElementType.equalsIgnoreCase("ValueKey")) {
			element = (MobileElement) driver.executeScript("flutter:waitFor", find.byValueKey(locatorValue), waitTime);
		} else if (flutterElementType.equalsIgnoreCase("Text")) {
			element = (MobileElement) driver.executeScript("flutter:waitFor", find.text(locatorValue), waitTime);
		} else {
			System.out.println("Unsupported Flutter Element Type:");
		}
        
		return element;
	}

**Comment by shibupanda** [comment]
@Prasea1993 could you please share Appium sever logs.

**Comment by Prasea1993** [comment]
I've used switchContext for flutter and Native app , so it was a workaroud for my problem.
