### ISSUE TITLE
Does pageBack() work?

### ISSUE THREAD

**Issue by Reppinger** [truongsinh/appium-flutter-driver#143]
I am using an Android emulator. 
Based on looking at the code and the Readme, it looks like I should be able to go back with the pageBack() finder.  I have the following Ruby code:
```
  def go_back
    finder = page_back 
    #finder Returns "eyJmaW5kZXJUeXBlIjoiUGFnZUJhY2sifQ=="
    back_element = ::Appium::Flutter::Element.new(@driver, finder: finder)
    #back_element Returns "#<Appium::Flutter::Element:0x..fbff8504109ff942c id=\"eyJmaW5kZXJUeXBlIjoiUGFnZUJhY2sifQ==\">"
    back_element.click
  end
```

Appium writes this to the log:
```
[debug] [MJSONWP (94282f11)] Calling AppiumDriver.click() with args: ["eyJmaW5kZXJUeXBlIjoiUGFnZUJhY2sifQ==","94282f11-1af0-4f9f-87d9-93144555686e"]
[debug] [FlutterDriver] Executing Flutter driver command 'click'
[debug] [FlutterDriver] >>> {"command":"tap","finderType":"PageBack"}
```

But nothing happens and it times out after a long time. The app never goes back.  

Am I doing something wrong?

**Comment by shibupanda** [comment]
@Reppinger is the application published in different language except English ?

**Comment by Reppinger** [comment]
Thanks for responding, @shibupanda .  No, our app is English only.

**Comment by shibupanda** [comment]
@Reppinger could you please check with flutter driver as well.

**Comment by Reppinger** [comment]
Sorry @shibupanda, I do not understanding your request.  Check if flutter driver is building with a non-English language?

**Comment by shibupanda** [comment]
@Reppinger I mean could you please the same test using flutter driver without Appium. Below may help you.

https://flutter.dev/docs/cookbook/testing/integration/introduction

**Comment by Reppinger** [comment]
Quick update: I haven't had a chance to do this yet. I will try writing a flutter driver test without appium that uses the device back.

**Comment by Reppinger** [comment]
@shibupanda I can't seem to get pageBack() to work in flutter_driver tests, either. I've been digging but have no idea why.  The app is English only. It takes a long time, times out and never clicks the back. Closing issue since it is not appium-flutter-driver.
