### ISSUE TITLE
integration_test replacing flutter_driver?

### ISSUE THREAD

**Issue by Reppinger** [truongsinh/appium-flutter-driver#150]
I'm really enjoying appium-flutter-driver and it is our team's preferred way to test our flutter apps. We are about to use it for a flutter web app (haven't tried that before).

However, the Flutter team has recently added the integration_test package into the flutter SDK. They are encouraging users to migrate away from flutter_driver.  An [article written by a Google Product Manager on Medium](https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e) talks about why they are going this direction.

So far, I know that we can not use integration_test for appium_flutter_driver because we need `enableFlutterDriverExtension()`. [Using integration_test](https://flutter.dev/docs/testing/integration-tests#migrating-from-flutter_driver) calls for us to _remove_ `enableFlutterDriverExtension()`.

Yet, flutter_driver was listed under **Dependencies** for the [integration_test package](https://pub.dev/packages/integration_test) before it was integrated into the SDK.  Maybe it still is a dependency?

I found one article that says flutter_driver is discontinued, but the author offered no reference or link to such an announcement. Further, the [docs for the flutter_driver API ](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) do not say anything about being deprecated or discontinued.

I want to continue using appium-flutter-driver and I am hoping someone knows more about this. The question for users and maintainers of appium_flutter_driver is, **_"Do we know if flutter_driver will be available for the foreseeable future?"_**

_Apologies for listing this as an issue, but I know this is a great, active community and I couldn't find anywhere else to start a discussion._

**Comment by jfortier882** [comment]
Was there any resolution on this? it's 2024 and the appium flutter driver is still using flutter_driver. I asked this question again in the discussions tab but idk how responsive this group is. 
@Reppinger are you still using this appium driver and still liking it? I'm just starting out with it, but am open to other automation tools if this one is outdated at this point.

**Comment by Reppinger** [comment]
I'm sorry Randy passed away in 2021. I need to close his account. Cathy Eppinger

**Comment by KazuCocoa** [comment]
It looks like this kind of discussion is still ongoing in the Flutter team as well. https://github.com/flutter/flutter/issues/148028

**Comment by saikrishna321** [comment]
We have build a new driver - https://github.com/AppiumTestDistribution/appium-flutter-integration-driver 

which is based in flutter integration test.

**Comment by saikrishna321** [comment]
Google3 recommends using integration_test package  https://github.com/flutter/flutter/issues/148028#issuecomment-2148960045
