### ISSUE TITLE
WaitFor not finding displayed element

### ISSUE THREAD

**Issue by funckytown1** [truongsinh/appium-flutter-driver#155]
I am using the flutter:waitFor command to check whether or not an element is displayed on screen however it is failing to recognize some elements and is timing out without finding them even though they are clearly displayed. For clarity the element is found and returned using the valueKey it is just not found by the waitFor command.
```
boolean isElementDisplayed;
setDriverContext(FLUTTER_CONTEXT);
MobileElement element = findElementByValueKey("key");
try {
     driver.executeScript("flutter:waitFor", element, FLUTTER_WAIT_TIME);
     isElementDisplayed = true;
     } catch (Exception ignored) {isElementDisplayed = false;}
```

Log for execute script

```
[MJSONWP (1cfd39ec)] Responding to client with driver.execute() result: "RenderView#0ac80\n │ debug mode enabled - android\n │ window size: Size(1080.0, 2028.0) (in physical pixels)\n │ device pixel ratio: 2.8 (physical pixels per logical pixel)\n │ configuration: Size(392.7, 737.5) at 2.8x (in logical pixels)\n │ semantics enabled\n │\n └─child: RenderSemanticsGestureHandler#63026\n   │ needs compositing\n   │ creator: _GestureSemantics ← RawGestureDetector ← GestureDetector\n   │   ← MyApp ← _InheritedProviderScope ←\n   │   ChangeNotifierProvider ← _NestedHook ←\n   │   _InheritedProviderScope ←\n   │   ChangeNotifierProvider ← _NestedHook ←\n   │   _InheritedProviderScope ←\n   │   ChangeNotifierProvider ← ⋯\n   │ parentData: \n   │ constraints: BoxConstraints(w=392.7, h=737.5)\n   │ semantics node: SemanticsNode#1\n   │ size: Size(392.7, 737.5)\n   │ behavior: deferToChild\n   │ gestures: tap\n   │\n   └─child: RenderPointerListener#e7fc0\n     │...
[HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/execute 200 180 ms - 358329
[HTTP] 
[HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context
[HTTP] {"name":"NATIVE_APP"}
[MJSONWP (1cfd39ec)] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","1cfd39ec-f05a-410a-8a17-c766562c4519"]
[FlutterDriver] Executing Flutter driver command 'setContext'
[MJSONWP (1cfd39ec)] Responding to client with driver.setContext() result: "NATIVE_APP"
[HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context 200 1 ms - 84
[HTTP] 
[HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/timeouts
[HTTP] {"type":"implicit","ms":0}
[MJSONWP (1cfd39ec)] Calling AppiumDriver.timeouts() with args: ["implicit",0,null,null,null,"1cfd39ec-f05a-410a-8a17-c766562c4519"]
[FlutterDriver] Executing proxied driver command 'timeouts'
[BaseDriver] MJSONWP timeout arguments: {"type":"implicit","ms":0}}
[BaseDriver] Set implicit wait to 0ms
[MJSONWP (1cfd39ec)] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/timeouts 200 1 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context
[HTTP] {"name":"FLUTTER"}
[MJSONWP (1cfd39ec)] Calling AppiumDriver.setContext() with args: ["FLUTTER","1cfd39ec-f05a-410a-8a17-c766562c4519"]
[FlutterDriver] Executing Flutter driver command 'setContext'
[MJSONWP (1cfd39ec)] Responding to client with driver.setContext() result: "FLUTTER"
[HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context 200 1 ms - 81
[HTTP] 
[HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/execute
[HTTP] {"script":"flutter:waitFor","args":[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0"},10]}
[MJSONWP (1cfd39ec)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0"},10],"1cfd39ec-f05a-410a-8a17-c766562c4519"]
[FlutterDriver] Executing Flutter driver command 'execute'
[FlutterDriver] >>> {"command":"waitFor","finderType":"ByValueKey","keyValueType":"String","keyValueString":"connectToKey","timeout":10000}
[FlutterDriver] <<< {"isError":true,"response":"Timeout while executing waitFor: TimeoutException after 0:00:10.000000: Future not completed\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command waitFor
[MJSONWP (1cfd39ec)] Encountered internal error running command: Error: Cannot execute command waitFor, server reponse {
[MJSONWP (1cfd39ec)]   "isError": true,
[MJSONWP (1cfd39ec)]   "response": "Timeout while executing waitFor: TimeoutException after 0:00:10.000000: Future not completed\n",
[MJSONWP (1cfd39ec)]   "type": "_extensionType",
[MJSONWP (1cfd39ec)]   "method": "ext.flutter.driver"
[MJSONWP (1cfd39ec)] }
[MJSONWP (1cfd39ec)]     at FlutterDriver.exports.executeElementCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:134:11)
[MJSONWP (1cfd39ec)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[MJSONWP (1cfd39ec)]     at Object.waitFor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:3)
[HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/execute 500
```

**Comment by yanivamram** [comment]
> I am using the flutter:waitFor command to check whether or not an element is displayed on screen however it is failing to recognize some elements and is timing out without finding them even though they are clearly displayed. For clarity the element is found and returned using the valueKey it is just not found by the waitFor command.
> 
> ```
> boolean isElementDisplayed;
> setDriverContext(FLUTTER_CONTEXT);
> MobileElement element = findElementByValueKey("key");
> try {
>      driver.executeScript("flutter:waitFor", element, FLUTTER_WAIT_TIME);
>      isElementDisplayed = true;
>      } catch (Exception ignored) {isElementDisplayed = false;}
> ```
> 
> Log for execute script
> 
> ```
> [MJSONWP (1cfd39ec)] Responding to client with driver.execute() result: "RenderView#0ac80\n │ debug mode enabled - android\n │ window size: Size(1080.0, 2028.0) (in physical pixels)\n │ device pixel ratio: 2.8 (physical pixels per logical pixel)\n │ configuration: Size(392.7, 737.5) at 2.8x (in logical pixels)\n │ semantics enabled\n │\n └─child: RenderSemanticsGestureHandler#63026\n   │ needs compositing\n   │ creator: _GestureSemantics ← RawGestureDetector ← GestureDetector\n   │   ← MyApp ← _InheritedProviderScope ←\n   │   ChangeNotifierProvider ← _NestedHook ←\n   │   _InheritedProviderScope ←\n   │   ChangeNotifierProvider ← _NestedHook ←\n   │   _InheritedProviderScope ←\n   │   ChangeNotifierProvider ← ⋯\n   │ parentData: \n   │ constraints: BoxConstraints(w=392.7, h=737.5)\n   │ semantics node: SemanticsNode#1\n   │ size: Size(392.7, 737.5)\n   │ behavior: deferToChild\n   │ gestures: tap\n   │\n   └─child: RenderPointerListener#e7fc0\n     │...
> [HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/execute 200 180 ms - 358329
> [HTTP] 
> [HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context
> [HTTP] {"name":"NATIVE_APP"}
> [MJSONWP (1cfd39ec)] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","1cfd39ec-f05a-410a-8a17-c766562c4519"]
> [FlutterDriver] Executing Flutter driver command 'setContext'
> [MJSONWP (1cfd39ec)] Responding to client with driver.setContext() result: "NATIVE_APP"
> [HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context 200 1 ms - 84
> [HTTP] 
> [HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/timeouts
> [HTTP] {"type":"implicit","ms":0}
> [MJSONWP (1cfd39ec)] Calling AppiumDriver.timeouts() with args: ["implicit",0,null,null,null,"1cfd39ec-f05a-410a-8a17-c766562c4519"]
> [FlutterDriver] Executing proxied driver command 'timeouts'
> [BaseDriver] MJSONWP timeout arguments: {"type":"implicit","ms":0}}
> [BaseDriver] Set implicit wait to 0ms
> [MJSONWP (1cfd39ec)] Responding to client with driver.timeouts() result: null
> [HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/timeouts 200 1 ms - 76
> [HTTP] 
> [HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context
> [HTTP] {"name":"FLUTTER"}
> [MJSONWP (1cfd39ec)] Calling AppiumDriver.setContext() with args: ["FLUTTER","1cfd39ec-f05a-410a-8a17-c766562c4519"]
> [FlutterDriver] Executing Flutter driver command 'setContext'
> [MJSONWP (1cfd39ec)] Responding to client with driver.setContext() result: "FLUTTER"
> [HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/context 200 1 ms - 81
> [HTTP] 
> [HTTP] --> POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/execute
> [HTTP] {"script":"flutter:waitFor","args":[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0"},10]}
> [MJSONWP (1cfd39ec)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFRvS2V5In0"},10],"1cfd39ec-f05a-410a-8a17-c766562c4519"]
> [FlutterDriver] Executing Flutter driver command 'execute'
> [FlutterDriver] >>> {"command":"waitFor","finderType":"ByValueKey","keyValueType":"String","keyValueString":"connectToKey","timeout":10000}
> [FlutterDriver] <<< {"isError":true,"response":"Timeout while executing waitFor: TimeoutException after 0:00:10.000000: Future not completed\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command waitFor
> [MJSONWP (1cfd39ec)] Encountered internal error running command: Error: Cannot execute command waitFor, server reponse {
> [MJSONWP (1cfd39ec)]   "isError": true,
> [MJSONWP (1cfd39ec)]   "response": "Timeout while executing waitFor: TimeoutException after 0:00:10.000000: Future not completed\n",
> [MJSONWP (1cfd39ec)]   "type": "_extensionType",
> [MJSONWP (1cfd39ec)]   "method": "ext.flutter.driver"
> [MJSONWP (1cfd39ec)] }
> [MJSONWP (1cfd39ec)]     at FlutterDriver.exports.executeElementCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:134:11)
> [MJSONWP (1cfd39ec)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
> [MJSONWP (1cfd39ec)]     at Object.waitFor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:3)
> [HTTP] <-- POST /wd/hub/session/1cfd39ec-f05a-410a-8a17-c766562c4519/execute 500
> ```

Hey,
Lately, I encounter with this issue more often.
Did you figure out what is the root cause for this issue?

**Comment by funckytown1** [comment]
For this instance it was a result of where the keys were created by our dev team in the flutter code and moving the keys instantiation to the lower level libraries fixed it. Another time the developers changed something with the nullability of string used to create the valuekey which fixed it. However I have run into the issue a few more times and am currently trying to figure out why the flutter driver is able to find certain elements on an Android 11, phone but can't find the exact same elements on an Android 8 phone despite being clearly displayed

**Comment by funckytown1** [comment]
@yanivamram 
Looks like animations in the app can cause this problem and the fix is setting the driver to run unsynchronized which is not a currently available feature in the appium-flutter driver 
https://github.com/flutter/flutter/issues/34503#issuecomment-503545683
