### ISSUE TITLE
About descendant finder in flutter_driver

### ISSUE THREAD

**Issue by yjf0824** [truongsinh/appium-flutter-driver#161]
https://github.com/truongsinh/appium-flutter-driver/blob/914cef350656f6281a8328b7450ab89e83b642bd/finder/python/appium_flutter_finder/flutter_finder.py#L81

If used in python3, base64.b64decode(serialized_finder) returns a byte string? And finder seems to be expected a dict, and json dumps return a string?
After modified local flutter finder code, I get the command output with following:
{"command":"get_text","finderType":"Descendant","matchRoot":false,"of_finderType":"ByValueKey","of_keyValueString":"video_name_skip","of_keyValueType":"String","matching_finderType":"ByValueKey","matching_keyValueString":"txt_skip","matching_keyValueType":"String"}
But I failed to get the target. However, I can get the element by_value_key 'video_name_skip', 'txt_skip' seperately.
How can I get the descendant element with python? Thanks.

**Comment by KazuCocoa** [comment]
Thanks for the report. Could you try out https://github.com/truongsinh/appium-flutter-driver/pull/163 ? (It is available as 0.1.4)

**Comment by yjf0824** [comment]
Thanks for reply. I have a question. If element layer of flutter as following:
layer1(ByValueKey "video_name_skip")
    -- layer2(ByValueKey "txt_skip_padding")
        -- layer3(ByValueKey "txt_skip")
I try to use:
    finder = FlutterFinder()
    key_finder = finder.by_value_key("video_name_skip")
    sub_key_finder = finder.by_value_key("txt_skip")
    final_finder = finder.by_descendant(key_finder, sub_key_finder)
    ele=FlutterElement(driver, final_finder)
    print(ele.text)

output:
    [debug] [FlutterDriver] Executing Flutter driver command 'getText'
[debug] [FlutterDriver] >>> {"command":"get_text","finderType":"Descendant","matchRoot":false,"of_finderType":"ByValueKey","of_keyValueString":"video_name_skip","of_keyValueType":"String","matching_finderType":"ByValueKey","matching_keyValueString":"txt_skip","matching_keyValueType":"String"}
[debug] [FlutterDriver] <<< {"isError":true,"response":"Uncaught extension error while executing get_text: Null check operator used on a null value\n#0      Descendant.deserialize (package:flutter_driver/src/common/find.dart:310:55)\n#1      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#2      FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:405:18)\n#3      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\n#4      new GetText.deserialize (package:flutter_driver/src/common/text.dart:15:97)\n#5      DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:49:39)\n#6      FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:425:18)\n#7      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:371:31)\n#8      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:597:32)\n<asynchronous suspension>\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command get_text
[debug] [MJSONWP (ae86ce36)] Encountered internal error running command: Error: Cannot execute command get_text, server reponse {
[debug] [MJSONWP (ae86ce36)]   "isError": true,
[debug] [MJSONWP (ae86ce36)]   "response": "Uncaught extension error while executing get_text: Null check operator used on a null value\n#0      Descendant.deserialize (package:flutter_driver/src/common/find.dart:310:55)\n#1      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#2      FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:405:18)\n#3      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\n#4      new GetText.deserialize (package:flutter_driver/src/common/text.dart:15:97)\n#5      DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:49:39)\n#6      FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:425:18)\n#7      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:371:31)\n#8      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:597:32)\n<asynchronous suspension>\n",
[debug] [MJSONWP (ae86ce36)]   "type": "_extensionType",
[debug] [MJSONWP (ae86ce36)]   "method": "ext.flutter.driver"
[debug] [MJSONWP (ae86ce36)] }
[debug] [MJSONWP (ae86ce36)]     at FlutterDriver.exports.executeElementCommand (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:126:11)
[debug] [MJSONWP (ae86ce36)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [MJSONWP (ae86ce36)]     at FlutterDriver.exports.getText (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/element.ts:4:20)

I could't find the root cause. What's wrong with my code? Thanks a lot!

**Comment by KazuCocoa** [comment]
I guess it tried to return null...

https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html
For example, the element should be null safety, but it had no value.
