### ISSUE TITLE
How to allow media or any other permissions?

### ISSUE THREAD

**Issue by laerciokonzen** [truongsinh/appium-flutter-driver#164]
My app allways ask for user permission when first installed and, running a simple test I allways get stuck because I can't get the "Allow" option of the permission window.
![image](https://user-images.githubusercontent.com/2004796/124476345-10f1de80-dd79-11eb-8652-4738ccb18f3d.png)

**Comment by KazuCocoa** [comment]
Will `"appium:autoGrantPermissions": true` help?
https://github.com/appium/appium-uiautomator2-driver
Afaik, the alert is by System, so this flutter-driver itself cannot interact with it. But this driver launches the app under test using appium-uiautomator2-driver. So this capability may help to allow/deny such permissions addressed in the manifest.

**Comment by laerciokonzen** [comment]
@KazuCocoa yeah, it works just by adding ```autoGrantPermissions: true``` to the capabilities option. Thank you.
