### ISSUE TITLE
Appium Flutter driver not working with version 1.21

### ISSUE THREAD

**Issue by Nut41tank** [truongsinh/appium-flutter-driver#166]
### Error with Appium Flutter driver
**Appium version** - Appium v1.21.0
**Flutter version** Flutter 2.2.3
**LOG from Appium server:**
![image](https://user-images.githubusercontent.com/26061580/125043479-2c385300-e0c5-11eb-92b1-0b70474d9d9d.png)

**Description:**
I try to test Flutter driver with Appium but when start test it show this error
**TypeError: Cannot read property 'toLowerCase' of undefined**
Not sure this is about Appium or Appium Flutter driver but when I test with other automation (UIAutomation etc) it work fine 
Please help check about this error 

Thank you

**Comment by KazuCocoa** [comment]
I guess this driver requires `deviceName` capabilities until 0.28.
Or I've improved some capabilities handler in a newer version. You could try out `appium@beta`.

**Comment by Nut41tank** [comment]
After try `appium@beta` it working now
Thank you

**Comment by Nut41tank** [comment]
Other question 
I want to know that Why UiAutomation2 is open along with Appium Flutter driver ? 
![image](https://user-images.githubusercontent.com/26061580/125058330-5ba28c00-e0d4-11eb-9c8b-29a6b321b545.png)

**Comment by KazuCocoa** [comment]
FlutterDriver depends on UIA2 driver to manage the app under test outside Dart VM world.
'FlutterDriver' handles only Dart VM (Flutter) communication over websocket connection ( https://www.headspin.io/blog/webinar/deep-dive-into-appium-for-flutter-app/ may help about this "websocket connection")
