### ISSUE TITLE
Unable to to find valuekeys

### ISSUE THREAD

**Issue by funckytown1** [truongsinh/appium-flutter-driver#168]
Unable to find certain value keys due to the use of an animation in our app. The following issue suggests a work around that seems to work but requires the use of runUnsynchronized which is not currently implemented.

https://github.com/flutter/flutter/issues/34503#issuecomment-503545683

**Comment by funckytown1** [comment]
@truongsinh @KazuCocoa @shibupanda 
The implementation of this method is looks like it will be critical for my testing. So I am thinking of attempting to implement it myself and am wondering you any of you have an idea of how difficult it would be or any suggestions on where to start?

**Comment by KazuCocoa** [comment]
I guess VSCode may help as development environment.
https://github.com/truongsinh/appium-flutter-driver/blob/b73941aefd4bae13fb92f84ffb3ec3b0731dfe31/driver/lib/commands/execute.ts probably be an entry point.
For example, `requestData` was added as https://github.com/truongsinh/appium-flutter-driver/commit/fca8588c400240d285d280eb21d072abb1dfe530 

You should find what command goes to Dart VM when your expected command is called first in flutter/dart VM layer before implementing appium-flutter-driver

**Comment by funckytown1** [comment]
Implemented setFrameSync which allowed for a fix!
