### ISSUE TITLE
 Connecting to Dart Observatory: ws://127.0.0.1:52872/EIE89oo878s=/ws

### ISSUE THREAD

**Issue by hongbiangoal** [truongsinh/appium-flutter-driver#18]
[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:52872/EIE89oo878s=/ws
[FlutterDriver] Error: connect ECONNREFUSED 127.0.0.1:52872
[FlutterDriver]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:52872/EIE89oo878s=/ws
[FlutterDriver] Waiting 300 seconds before trying...

please help me ~ thanks

**Comment by shibupanda** [comment]
@hongbiangoal Could you please send us to complete logs using gist.

**Comment by hongbiangoal** [comment]
gist:a45d27cbb9cd80b967c407d5e0df975c

**Comment by hongbiangoal** [comment]
https://gist.github.com/hongbiangoal/a45d27cbb9cd80b967c407d5e0df975c

**Comment by shibupanda** [comment]
@hongbiangoal I got below in the given logs.

 **Error: Couldn't start port forwarding on port 8202. Please provide a different port using 'wdaLocalPort' capability
2019-09-11 09:40:35:258 [XCUITest]     at WebDriverAgent.createIProxy (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver/lib/wda/webdriveragent.js:263:13)**

Didn't get any flutter related error.
Please use the available port in wdaLocalPort capability.

**Comment by hongbiangoal** [comment]
I use available port,  but failed!

**Comment by hongbiangoal** [comment]
WebDriverAgent successfully started after 6969ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1568195760633 (17:56:00 GMT+0800 (中国标准时间))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8402/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.example.helloWorld","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"E3893CD7-CDBD-408E-9E67-91223B3E1D1E","capabilities":{"device":"iphone","browserName":"hello_world","sdkVersion":"12.4.1","CFBundleIdentifier":"com.example.helloWorld"}},"sessionId":"E3893CD7-CDBD-408E-9E67-91223B3E1D1E"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1568195763123 (17:56:03 GMT+0800 (中国标准时间))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1568195763123 (17:56:03 GMT+0800 (中国标准时间))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1568195763123 (17:56:03 GMT+0800 (中国标准时间))
[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:54061/OP35kYReO6Q=/ws
[FlutterDriver] Error: connect ECONNREFUSED 127.0.0.1:54061
[FlutterDriver]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:54061/OP35kYReO6Q=/ws
[FlutterDriver] Waiting 300 seconds before trying...



it seems ws's port not listen

**Comment by shibupanda** [comment]
Ok, will try to reproduce here and get back to you.
@truongsinh Any points you want to add here if you faced this earlier.

**Comment by truongsinh** [comment]
@hongbiangoal are using app-under-test in release, profile or debug mode?

**Comment by KazuCocoa** [comment]
If the issue is communication with real iPhone, I guess this is because port forward.
We're improving the logic like https://github.com/appium/appium-xcuitest-driver/pull/1066
I guess you need to establish a connection to `54061` on the real device from this driver.


---

Probably flutter uses iproxy to achieve it. https://github.com/flutter/flutter/search?q=iproxy&unscoped_q=iproxy
(Appium replaced from iproxy to our own implementation for the usage)

**Comment by hongbiangoal** [comment]
@truongsinh  yes
@KazuCocoa  thanks，the port foward has work ok~~

**Comment by hongbiangoal** [comment]
resolved by iproxy localport  deviceport

**Comment by vijaydeepak-rezi** [comment]
Can you explain how to Fix this issue . Even am facing the Same issue @hongbiangoal @KazuCocoa

**Comment by antonydass** [comment]
Hi All, 

I am also facing the same issue. Please help to resolve this issue.

**Comment by haibgit** [comment]
I've same issues when run with android virual 9.0 google play.
I using app hello_word in default flutter C:\flutter\examples\hello_world
I using https://pypi.org/project/Appium-Flutter-Finder  version 0.1.3
