### ISSUE TITLE
Did flutter-driver  support Python?

### ISSUE THREAD

**Issue by 0x88l** [truongsinh/appium-flutter-driver#22]
Ni Hao, truongsinh~
Did flutter-driver  support Python?

**Comment by shibupanda** [comment]
@0x88l we need to take this as feature as python binding is not yet available for appium-flutter-finder.
@truongsinh Could you please mark this as feature request.

**Comment by truongsinh** [comment]
Current we don't, PRs are welcome

**Comment by truongsinh** [comment]
To give more context, the expansion to other languages can exampled by this PR https://github.com/truongsinh/appium-flutter-driver/pull/35

**Comment by shibupanda** [comment]
@0x88l Now python finder is added in this repository. Please have a look.
@KazuCocoa Thanks.

**Comment by nowo** [comment]
> @0x88l Now python finder is added in this repository. Please have a look.
> @KazuCocoa Thanks.

How can i import the flutter library in appium test file ?

**Comment by shibupanda** [comment]
@nowo 
It's available in pypi org.
Do 
pip install Appium-Flutter-Finder to use the finder.

**Comment by KazuCocoa** [comment]
and https://github.com/truongsinh/appium-flutter-driver/blob/master/example/python/example.py is a simple example to import it
