### ISSUE TITLE
Need Help to create kotlin jar to use that in java

### ISSUE THREAD

**Issue by shibupanda** [truongsinh/appium-flutter-driver#23]
Hi @truongsinh could you please help me to build a jar as I tried and it leads to below error.
java -jar appium-flutter-finder-0.0.4.jar 
no main manifest attribute, in appium-flutter-finder-0.0.4.jar

If possible please help me with the jar link.
That would really help for java user.

**Comment by truongsinh** [comment]
@shibupanda I don't think you can run ```java -jar appium-flutter-finder-0.0.4.jar``` directly, but you have to declare this as dependency. Please find the example at https://github.com/truongsinh/appium-flutter-driver/blob/master/example/java/pom.xml, specifically line https://github.com/truongsinh/appium-flutter-driver/blob/master/example/java/pom.xml#L52-L56 and https://github.com/truongsinh/appium-flutter-driver/blob/master/example/java/pom.xml#L88-L91

**Comment by shibupanda** [comment]
@truongsinh Yes you are absolutely correct.
But I did only for the verification whether the build is correct or not. I am using "gradle clean build" command to build the jar.

When I used the built jar in the project it leads with the below error.

https://gist.github.com/shibupanda/662770f842224283248b603d16f0351c

**Comment by shibupanda** [comment]
Hi @truongsinh 
Any suggestion on the above.

**Comment by truongsinh** [comment]
@shibupanda it seems your project does not have any `kotlin` depedency, which is required. It's kind of weird because `appium-flutter-driver` should already depend on `kotlin` std. Maybe you need to declare "transitive" :-? It's better if you have the whole project available for me to run on my local machine.

**Comment by truongsinh** [comment]
You can also look at this https://stackoverflow.com/questions/44197521/gradle-project-java-lang-noclassdeffounderror-kotlin-jvm-internal-intrinsics/44583514

**Comment by shibupanda** [comment]
Hi @truongsinh I took the pull from kotlin-finder branch as I don't want to invest time to build whole using java. If there is any issue with the branch I may start creating the java binding for finder.

**Comment by truongsinh** [comment]
> I think you have merged it into master. But to start I think we need to buld jar and there I am facing issue.

Yes it was merged to master. Were you able to run the Java example provided?

**Comment by shibupanda** [comment]
No @truongsinh I am not as the dependency is not in maven so I am getting dependecy error in pom.
That's why I am trying to the jar.

**Comment by shibupanda** [comment]
Hi @truongsinh any update on the above.
Thanks

**Comment by ahashmi24** [comment]
Hi @truongsinh 
I have tried to execute your java example code after installing appium-flutter-driver as mentioned in [link](https://www.npmjs.com/package/appium-flutter-driver) and setting up the maven dependencies by keeping 'repository' folder in my local machine. However, I am getting issue "**UnhandledPromiseRejectionWarning: Error: "ext.flutter.driver" is not found in "extensionRPCs"**" after launching the android app on real device.

You can see the complete log below:
https://gist.github.com/ahashmi24/1d77c19f6dfba4648f8202a169c50bda

**Comment by shibupanda** [comment]
@ahashmi24 where you got repository folder. Can you help me with the link. As I am trying to build jar but stuck due to above error.

**Comment by ahashmi24** [comment]
@shibupanda 
You can download it from [link](https://github.com/truongsinh/appium-flutter-driver/releases/download/kotlin-finder-0.0.3/repository.zip) and take reference from [pom.xml](https://github.com/truongsinh/appium-flutter-driver/blob/master/example/java/pom.xml)

Happy Testing!!!

**Comment by shibupanda** [comment]
Hi @ahashmi24 could you please create a new thread for the issue you reported as it seems the driver is not configure properly. Expect you to create a new thread so that we can track the issues easily.
