### ISSUE TITLE
Error While Running in ios real Device 

### ISSUE THREAD

**Issue by vijaydeepak-rezi** [truongsinh/appium-flutter-driver#26]
@truongsinh 
```
[BaseDriver] Unzipped local app to '/var/folders/2g/drs1ttp963lc1g02ybpsq2sc0000gn/T/20191029-55614-1dqwcxe.0lngg/Payload/Runner.app'
[XCUITest] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[XCUITest]     at makeStatsCallback (fs.js:161:11)
[XCUITest]     at Object.fs.stat (fs.js:896:14)
[XCUITest]     at Object.stat (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:15:23)
[XCUITest]     at _bluebird.default.map (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-support/lib/util.js:260:72)
[XCUITest]     at tryCatcher (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/map.js:68:38)
[XCUITest]     at MappingPromiseArray.PromiseArray._iterate (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promise_array.js:115:31)
[XCUITest]     at MappingPromiseArray.init (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promise_array.js:79:10)
[XCUITest]     at MappingPromiseArray._asyncInit (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/map.js:37:10)
[XCUITest]     at _drainQueueStep (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:97:12)
[XCUITest]     at _drainQueue (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:86:9)
[XCUITest]     at Async._drainQueues (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:102:5)
[XCUITest]     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:15:14)
[XCUITest]     at runCallback (timers.js:696:18)
[XCUITest]     at tryOnImmediate (timers.js:667:5)
[XCUITest]     at processImmediate (timers.js:649:5)
[DevCon Factory] Releasing connections for c85d7cb996a05d26abb89c93df86d62af5486f1f device on any port number
[DevCon Factory] No cached connections have been found
```

**Comment by truongsinh** [comment]
@vijaydeepak-rezi admittedly I have not tried this on iOS real device. Are you running the example provided in this repo?

**Comment by vijaydeepak-rezi** [comment]
@truongsinh  i've create a dummy project to test  on the real device

**Comment by shibupanda** [comment]
@vijaydeepak-rezi could you please send the complete appium logs for better debugging. And please let us know whether you are using the sample App.

**Comment by vijaydeepak-rezi** [comment]
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.15.0-beta.0 creating new FlutterDriver (v0.0.20) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: /Users/Vijay/Desktop/Runner_flutter/Runner.ipa
[Appium]   automationName: Flutter
[Appium]   deviceName: A1
[Appium]   newCommandTimeout: 18000
[Appium]   noReset: true
[Appium]   platformVersion: 13.2
[Appium]   udid: c85d7cb996a05d26abb89c93df86d62af5486f1f
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "app": "/Users/Vijay/Desktop/Runner_flutter/Runner.ipa",
[debug] [BaseDriver]   "noReset": true,
[debug] [BaseDriver]   "newCommandTimeout": "18000",
[debug] [BaseDriver]   "platformVersion": "13.2",
[debug] [BaseDriver]   "automationName": "Flutter",
[debug] [BaseDriver]   "bundleId": "com.Vijay.rezi",
[debug] [BaseDriver]   "platformName": "iOS",
[debug] [BaseDriver]   "udid": "c85d7cb996a05d26abb89c93df86d62af5486f1f",
[debug] [BaseDriver]   "deviceName": "A1"
[debug] [BaseDriver] }
[BaseDriver] Capability 'newCommandTimeout' changed from string ('18000') to integer (18000). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   bundleId
[BaseDriver] Session created with session id: 1177131e-4066-44df-a7be-21e029f3527e
[FlutterDriver] Starting an IOS proxy session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "app": "/Users/Vijay/Desktop/Runner_flutter/Runner.ipa",
[debug] [BaseDriver]   "noReset": true,
[debug] [BaseDriver]   "newCommandTimeout": 0,
[debug] [BaseDriver]   "platformVersion": "13.2",
[debug] [BaseDriver]   "automationName": "Flutter",
[debug] [BaseDriver]   "bundleId": "com.Vijay.rezi",
[debug] [BaseDriver]   "platformName": "iOS",
[debug] [BaseDriver]   "udid": "c85d7cb996a05d26abb89c93df86d62af5486f1f",
[debug] [BaseDriver]   "deviceName": "A1"
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: a147dea1-674b-447a-b48d-0661d55ff2d6
[debug] [XCUITest] Current user: 'honeywell'
[debug] [XCUITest] Available devices: c85d7cb996a05d26abb89c93df86d62af5486f1f
[debug] [XCUITest] Creating iDevice object with udid 'c85d7cb996a05d26abb89c93df86d62af5486f1f'
[XCUITest] Determining device to run tests on: udid: 'c85d7cb996a05d26abb89c93df86d62af5486f1f', real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1575011869534 (12:47:49 GMT+0530 (IST))
[BaseDriver] Using local app '/Users/Vijay/Desktop/Runner_flutter/Runner.ipa'
[debug] [BaseDriver] Unzipping '/Users/Vijay/Desktop/Runner_flutter/Runner.ipa'
[debug] [BaseDriver] Extracted 646 item(s) from '/Users/Vijay/Desktop/Runner_flutter/Runner.ipa'
[debug] [BaseDriver] Matched 644 item(s) in the extracted archive. Assuming 'Payload/Runner.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/2g/drs1ttp963lc1g02ybpsq2sc0000gn/T/20191029-97337-yjwqp5.7aib/Payload/Runner.app'
[XCUITest] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[XCUITest]     at makeStatsCallback (fs.js:161:11)
[XCUITest]     at Object.fs.stat (fs.js:896:14)
[XCUITest]     at Object.stat (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:15:23)
[XCUITest]     at _bluebird.default.map (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-support/lib/util.js:260:72)
[XCUITest]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/map.js:68:38)
[XCUITest]     at MappingPromiseArray.PromiseArray._iterate (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promise_array.js:115:31)
[XCUITest]     at MappingPromiseArray.init (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promise_array.js:79:10)
[XCUITest]     at MappingPromiseArray._asyncInit (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/map.js:37:10)
[XCUITest]     at _drainQueueStep (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:97:12)
[XCUITest]     at _drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:86:9)
[XCUITest]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:102:5)
[XCUITest]     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:15:14)
[XCUITest]     at runCallback (timers.js:696:18)
[XCUITest]     at tryOnImmediate (timers.js:667:5)
[XCUITest]     at processImmediate (timers.js:649:5)
[DevCon Factory] Releasing connections for c85d7cb996a05d26abb89c93df86d62af5486f1f device on any port number
[DevCon Factory] No cached connections have been found
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1575011871722 (12:47:51 GMT+0530 (IST))
[debug] [W3C] Encountered internal error running command: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[debug] [W3C]     at makeStatsCallback (fs.js:161:11)
[debug] [W3C]     at Object.fs.stat (fs.js:896:14)
[debug] [W3C]     at Object.stat (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/util.js:16:23)
[debug] [W3C]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:15:23)
[debug] [W3C]     at _bluebird.default.map (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-support/lib/util.js:260:72)
[debug] [W3C]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/util.js:16:23)
[debug] [W3C]     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/map.js:68:38)
[debug] [W3C]     at MappingPromiseArray.PromiseArray._iterate (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promise_array.js:115:31)
[debug] [W3C]     at MappingPromiseArray.init (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/promise_array.js:79:10)
[debug] [W3C]     at MappingPromiseArray._asyncInit (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/map.js:37:10)
[debug] [W3C]     at _drainQueueStep (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:97:12)
[debug] [W3C]     at _drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:86:9)
[debug] [W3C]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:102:5)
[debug] [W3C]     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/bluebird/js/release/async.js:15:14)
[debug] [W3C]     at runCallback (timers.js:696:18)
[debug] [W3C]     at tryOnImmediate (timers.js:667:5)
[debug] [W3C]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session 500 2306 ms - 618
[HTTP]

**Comment by vijaydeepak-rezi** [comment]
> @vijaydeepak-rezi could you please send the complete appium logs for better debugging. And please let us know whether you are using the sample App.

@shibupanda  : Had build a sample app using my developer Account and trying run on real device

**Comment by vijaydeepak-rezi** [comment]
Anyone was able to run on iOS Real Device  ?  If so can you please let me know the Configurations
