### ISSUE TITLE
Getting issue "UnhandledPromiseRejectionWarning: Error: "ext.flutter.driver" is not found in "extensionRPCs

### ISSUE THREAD

**Issue by ahashmi24** [truongsinh/appium-flutter-driver#27]
Hi @truongsinh 
I have tried to execute your java example code after installing appium-flutter-driver as mentioned in link and setting up the maven dependencies by keeping 'repository' folder in my local machine. However, I am getting issue "UnhandledPromiseRejectionWarning: Error: "ext.flutter.driver" is not found in "extensionRPCs"" after launching the android app on real device.

You can see the complete log below:
https://gist.github.com/ahashmi24/1d77c19f6dfba4648f8202a169c50bda

**Comment by shibupanda** [comment]
Hi @ahashmi24 Can I get some more information here. Which dart version you have installed and set in environment.

**Comment by ahashmi24** [comment]
@shibupanda 
its 2.6.1 
$ dart --version
Dart VM version: 2.6.1 (Mon Nov 11 13:12:24 2019 +0100) on "macos_x64"

do I need to set path variable for dart? can you help me what path I need to set?

**Comment by shibupanda** [comment]
Sure I can help you tomorrow. I have one more question whether you are trying with the sample apk what is here in this repo.

**Comment by ahashmi24** [comment]
I tried with a dummy flutter debug app received from my development team.

**Comment by shibupanda** [comment]
Please ask the dev team to add enableFlutterDriverExtension() in main.dart. This will help you to resolve the issue.

**Comment by ahashmi24** [comment]
Yes. I tried with the apk present in this repo and able to execute the sample java code successfully.

Can you guide me on how we can inspect the element locator in flutter app?

**Comment by sahanaprasad** [comment]
Is this issue resolved @ahashmi24? I have been trying to automate the flutter embedded native app and currently blocked by this issue. I have tried in couple of devices and EMULATORS. Tried with beta version of appium as well, but no luck. I have enabled flutter driver extension in the flutter app. I'm work on the macOS, catalina. Tried withh android API version 24/26. Appium version: 1.19 beta v. Flutter version 1.15 beta. Below is the appium log for the particular error. The app is in debug mode and flutter driver enabled. @ahashmi24  @shibupanda 


 Connecting to Dart Observatory: ws://127.0.0.1:36528/Rrge3Rw_Y3I=/ws
[FlutterDriver] Connected to ws://127.0.0.1:36528/Rrge3Rw_Y3I=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3790685036181395","name":"main","number":"3790685036181395"}]
[FlutterDriver] "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.scheduleFrame","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion","ext.flutter.reassemble","ext.flutter.exit","ext.flutter.saveCompilationTrace","ext.flutter.platformOverride","ext.flutter.evict","ext.flutter.timeDilation","ext.flutter.debugPaint","ext.flutter.debugPaintBaselinesEnabled","ext.flutter.repaintRainbow","ext.flutter.debugCheckElevationsEnabled","ext.flutter.debugDumpLayerTree","ext.flutter.debugDumpRenderTree","ext.flutter.debugDumpSemanticsTreeInTraversalOrder","ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder","ext.flutter.debugDumpApp","ext.flutter.showPerformanceOverlay","ext.flutter.didSendFirstFrameEvent","ext.flutter.didSendFirstFrameRasterizedEvent","ext.flutter.fastReassemble","ext.flutter.profileWidgetBuilds","ext.flutter.debugAllowBanner","ext.flutter.debugWidgetInspector","ext.flutter.inspector.structuredErrors","ext.flutter.inspector.show","ext.flutter.inspector.trackRebuildDirtyWidgets","ext.flutter.inspector.trackRepaintWidgets","ext.flutter.inspector.disposeAllGroups","ext.flutter.inspector.disposeGroup","ext.flutter.inspector.isWidgetTreeReady","ext.flutter.inspector.disposeId","ext.flutter.inspector.setPubRootDirectories","ext.flutter.inspector.setSelectionById","ext.flutter.inspector.getParentChain","ext.flutter.inspector.getProperties","ext.flutter.inspector.getChildren","ext.flutter.inspector.getChildrenSummaryTree","ext.flutter.inspector.getChildrenDetailsSubtree","ext.flutter.inspector.getRootWidget","ext.flutter.inspector.getRootRenderObject","ext.flutter.inspector.getRootWidgetSummaryTree","ext.flutter.inspector.getDetailsSubtree","ext.flutter.inspector.getSelectedRenderObject","ext.flutter.inspector.getSelectedWidget","ext.flutter.inspector.getSelectedSummaryWidget","ext.flutter.inspector.isWidgetCreationTracked","ext.flutter.inspector.screenshot","ext.dart.io.getOpenFiles","ext.dart.io.getFileByID"]

**Comment by shibupanda** [comment]
Did you try with our sample app? Please try with that whether you are getting same.

**Comment by sahanaprasad** [comment]
Yes it works with the sample app. @shibupanda

**Comment by basilmariano** [comment]
have you manage to fix this issue? because im also getting this

**Comment by rahulacko** [comment]
I am also facing the same. This project only works on Sample apps. I couldn't find any one who is successfully able to automate his flutter app

**Comment by sahanaprasad** [comment]
I managed to resolve this issue. It is solely because the flutter driver extension was not enabled. Please make sure you enable it in the proper main function of your app. I also got this issue when I used the emulator. try using the real device instead if you still face the issue.

**Comment by rahulacko** [comment]
yeah, flutter driver extension is enabled. I can try it on a real device.

**Comment by rahulacko** [comment]
If we just use the flutter apk given by developers and launch it using node js script. I dont see flutter inspector would be able to identify that

**Comment by windows7lake** [comment]
I faced this trouble too. And I run script on Android 8.0 (AUZS) but not succuss on Android (Pixel 3). 
```
[debug] [FlutterDriver] /Users/yinglin/Library/Android/sdk/platform-tools/adb forward tcp:38635 tcp:38635
[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:38635/75FRNTyRY9U=/ws
[FlutterDriver] Connected to ws://127.0.0.1:38635/75FRNTyRY9U=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/2822088795645635","name":"main","number":"2822088795645635","isSystemIsolate":false}]
[FlutterDriver] "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.scheduleFrame","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.httpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.socketProfilingEnabled","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion","ext.flutter.reassemble","ext.flutter.exit","ext.flutter.platformOverride","ext.flutter.brightnessOverride","ext.flutter.connectedVmServiceUri","ext.flutter.activeDevToolsServerAddress","ext.flutter.timeDilation","ext.flutter.evict","ext.flutter.invertOversizedImages","ext.flutter.debugPaint","ext.flutter.debugPaintBaselinesEnabled","ext.flutter.repaintRainbow","ext.flutter.debugCheckElevationsEnabled","ext.flutter.debugDumpLayerTree","ext.flutter.debugDumpRenderTree","ext.flutter.debugDumpSemanticsTreeInTraversalOrder","ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder","ext.flutter.debugDumpApp","ext.flutter.showPerformanceOverlay","ext.flutter.didSendFirstFrameEvent","ext.flutter.didSendFirstFrameRasterizedEvent","ext.flutter.fastReassemble","ext.flutter.profileWidgetBuilds","ext.flutter.debugAllowBanner","ext.flutter.debugWidgetInspector","ext.flutter.inspector.structuredErrors","ext.flutter.inspector.show","ext.flutter.inspector.trackRebuildDirtyWidgets","ext.flutter.inspector.trackRepaintWidgets","ext.flutter.inspector.disposeAllGroups","ext.flutter.inspector.disposeGroup","ext.flutter.inspector.isWidgetTreeReady","ext.flutter.inspector.disposeId","ext.flutter.inspector.setPubRootDirectories","ext.flutter.inspector.setSelectionById","ext.flutter.inspector.getParentChain","ext.flutter.inspector.getProperties","ext.flutter.inspector.getChildren","ext.flutter.inspector.getChildrenSummaryTree","ext.flutter.inspector.getChildrenDetailsSubtree","ext.flutter.inspector.getRootWidget","ext.flutter.inspector.getRootRenderObject","ext.flutter.inspector.getRootWidgetSummaryTree","ext.flutter.inspector.getDetailsSubtree","ext.flutter.inspector.getSelectedRenderObject","ext.flutter.inspector.getSelectedWidget","ext.flutter.inspector.getSelectedSummaryWidget","ext.flutter.inspector.isWidgetCreationTracked","ext.flutter.inspector.screenshot"]
[FlutterDriver] Waiting 300 seconds before trying...
[FlutterDriver] Attempt #3
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:42373/RJYyAw5uxfo=/ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:42373/RJYyAw5uxfo=/ws
[FlutterDriver] Waiting 300 seconds before trying...
[FlutterDriver] Attempt #3
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:38387/tKL6692u-7U=/ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:38387/tKL6692u-7U=/ws
[FlutterDriver] Waiting 300 seconds before trying...
[FlutterDriver] Attempt #3
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:38055/Lr6oD_4w_UY=/ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:38055/Lr6oD_4w_UY=/ws
[FlutterDriver] Waiting 300 seconds before trying...
[FlutterDriver] Attempt #3
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:37653/xwEKKr6rWqU=/ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:37653/xwEKKr6rWqU=/ws
[FlutterDriver] Waiting 300 seconds before trying...
```

**Comment by windows7lake** [comment]
@sahanaprasad

**Comment by rahulacko** [comment]
I am using an android emulator. Every time I launch the app it waits for 300 seconds. Not sure what is it looking for 300 seconds and after that execute my script.
Flutter 2.3.0-13.0.pre.163 
Dart SDK version: 2.14.0-145.0.dev

Please find the below appium logs -
 Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:37293/voIGKR1q_Bg=/ws
[FlutterDriver] Connected to ws://127.0.0.1:37293/voIGKR1q_Bg=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/4237714639904655","name":"main","number":"4237714639904655","isSystemIsolate":false}]
[FlutterDriver] "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.scheduleFrame","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.httpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.socketProfilingEnabled","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion"]
[FlutterDriver] Waiting 300 seconds before trying...
[FlutterDriver] Attempt #2
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:37293/voIGKR1q_Bg=/ws
[FlutterDriver] Connected to ws://127.0.0.1:37293/voIGKR1q_Bg=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/4237714639904655","name":"main","number":"4237714639904655","isSystemIsolate":false}]
[Appium] New FlutterDriver session created successfully, session 3b61e2b5-c261-4393-ad18-f7f05c31e32d added to master session list

**Comment by M1qa** [comment]
@shibupanda ，I meet a smaple problem,can you help me?                                                                                       
 [FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:41797/8aYb1L-aqlA=/ws
[FlutterDriver] Connected to ws://127.0.0.1:41797/8aYb1L-aqlA=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3924594382217443","name":"main","number":"3924594382217443","isSystemIsolate":false}]
[FlutterDriver] "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.scheduleFrame","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.httpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.socketProfilingEnabled","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion","ext.dart.io.getHttpProfile","ext.dart.io.getHttpProfileRequest","ext.dart.io.clearHttpProfile"]
[FlutterDriver] Waiting 300 seconds before trying...
