### ISSUE TITLE
Error in transferring metadata 

### ISSUE THREAD

**Issue by hattersharath** [truongsinh/appium-flutter-driver#29]
POM file - 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.saucelabs</groupId>
	<artifactId>sauce_appium_junit</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>sauce_appium_junit</name>
	<description>Sample Appium tests using JUnit</description>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>5.0.0-BETA8</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>com.saucelabs</groupId>
			<artifactId>sauce_junit</artifactId>
			<version>2.1.23</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.2.4</version>
		</dependency>

		
		<dependency>
			<groupId>pro.truongsinh</groupId>
			<artifactId>appium-flutter-finder</artifactId>
			<version>0.0.4</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>saucelabs-repository</id>
			<url>https://repository-saucelabs.forge.cloudbees.com/release</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>local-maven-repo</id>
			<url>file:///Users/truongsinh/Dev/flutter/appium-flutter-driver/finder/kotlin/build/repository</url>
		</repository>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
	</repositories>
</project>

Error response - 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sauce_appium_junit 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.httpcomponents:httpcore:jar:4.4.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] Downloading: https://repository-saucelabs.forge.cloudbees.com/release/org/seleniumhq/selenium/selenium-api/maven-metadata.xml
[WARNING] Could not transfer metadata org.seleniumhq.selenium:selenium-api/maven-metadata.xml from/to saucelabs-repository (https://repository-saucelabs.forge.cloudbees.com/release): repository-saucelabs.forge.cloudbees.com
[INFO] Downloading: https://repository-saucelabs.forge.cloudbees.com/release/org/seleniumhq/selenium/selenium-support/maven-metadata.xml
[WARNING] Could not transfer metadata org.seleniumhq.selenium:selenium-support/maven-metadata.xml from/to saucelabs-repository (https://repository-saucelabs.forge.cloudbees.com/release): repository-saucelabs.forge.cloudbees.com
[INFO] Downloading: https://repository-saucelabs.forge.cloudbees.com/release/pro/truongsinh/appium-flutter-finder/0.0.4/appium-flutter-finder-0.0.4.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.975 s
[INFO] Finished at: 2019-12-09T12:35:58+04:00
[INFO] Final Memory: 12M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sauce_appium_junit: Could not resolve dependencies for project com.saucelabs:sauce_appium_junit:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at pro.truongsinh:appium-flutter-finder:jar:0.0.4: Failed to read artifact descriptor for pro.truongsinh:appium-flutter-finder:jar:0.0.4: Could not transfer artifact pro.truongsinh:appium-flutter-finder:pom:0.0.4 from/to saucelabs-repository (https://repository-saucelabs.forge.cloudbees.com/release): repository-saucelabs.forge.cloudbees.com: Unknown host repository-saucelabs.forge.cloudbees.com -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

URL - https://repository-saucelabs.forge.cloudbees.com/release - is not found
URL - file:///Users/truongsinh/Dev/flutter/appium-flutter-driver/finder/kotlin/build/repository - do we need to change this in my machine?

**Comment by ahashmi24** [comment]
@hattersharath 
is the below location exists in your local machine?
Users/truongsinh/Dev/flutter/appium-flutter-driver/finder/kotlin/build/repository

**Comment by hattersharath** [comment]
@ahashmi24 
No, it is not there.
Do I need to create a new empty folder for this in my local?

**Comment by shibupanda** [comment]
Hi @hattersharath 
https://github.com/truongsinh/appium-flutter-driver/releases 
Download the repository.zip file extract it open the folder and get the jar file and use mvn command to place that jar inside your local repository or add directly in the build path and comment which is not needed for your project in pom.xml.

**Comment by hattersharath** [comment]
@shibupanda Thank you, have done that.
But URL - https://repository-saucelabs.forge.cloudbees.com/release is not reachable.

**Comment by shibupanda** [comment]
@hattersharath you can comment those if it is not required for you.

**Comment by hattersharath** [comment]
@shibupanda thank you
