### ISSUE TITLE
"flutter: waitFor" command is not getting time out after waiting enough time to FlutterElement visible on screen. 

### ISSUE THREAD

**Issue by ahashmi24** [truongsinh/appium-flutter-driver#30]
@truongsinh 
Can we add any default time out for this command or there is any way to define explicit wait time for this command. Same for WaitForAbsent command.

**Comment by shibupanda** [comment]
Hi @ahashmi24 good catch.
@truongsinh I think **timeoutDuration** parameter is missed in driver. We need to add.

**Comment by ahashmi24** [comment]
@truongsinh 
Any update on it?

**Comment by ahashmi24** [comment]
@shibupanda @truongsinh 
Any updates?

**Comment by ahashmi24** [comment]
@truongsinh @shibupanda 
Can you guys please look into this issue. It blocks me to fail the test step.

**Comment by alikillz** [comment]
any news regarding this issue?

**Comment by shibupanda** [comment]
@ahashmi24 and @alikillz 
Development is going on we'll update soon.

**Comment by truongsinh** [comment]
@other: sorry for such a lateeeeee reply.
@shibupanda are you working on this one? If you are then I can focus on others.

**Comment by shibupanda** [comment]
@truongsinh am working on it soon I will send you my first pull request

**Comment by ahashmi24** [comment]
@shibupanda Thank-You for the fixes.

should I need to re-install appium to utilize these fixes?

Currently, I am using v1.16.0

**Comment by shibupanda** [comment]
@ahashmi24 Please use latest version of driver in appium 1.16.0
https://www.npmjs.com/package/appium-flutter-driver

**Comment by ahashmi24** [comment]
@shibupanda 
is this a correct version? 
appium-flutter-driver@0.0.20

**Comment by shibupanda** [comment]
@ahashmi24 
appium-flutter-driver@0.0.21 is the latest versions publish few hours ago.
