### ISSUE TITLE
driver.context('FLUTTER') can't work

### ISSUE THREAD

**Issue by LDouble** [truongsinh/appium-flutter-driver#32]
hi, I use uiautomator2 as the automationName when  I start my app. and  I use driver.context('FLUTTER') to switch the driver. there are some wrongs.
```
org.openqa.selenium.remote.SessionNotFoundException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
```

**Comment by tiendung01023** [comment]
I had the same problem as you, how did you solve it?

**Comment by tiendung01023** [comment]
@LDouble

**Comment by giangthao** [comment]
After switch context to NATIVE, I can't catch xpath even though I can run app in background   await driver.switchContext('NATIVE_APP');
      await driver.saveScreenshot('./native-screenshot.png');
      driver.background(10)
     // await driver.back();
      await driver.pause(3000)
      await (await await driver.$('//android.widget.ImageView[@content-desc="Project\n Tab 2 of 4"]')).click();

**Comment by KazuCocoa** [comment]
Please create a new issue with the full server log

**Comment by tharun-pothuraj-wdc** [comment]
@KazuCocoa I created a new ticket with the full error stack trace. Here is the new ticket: https://github.com/appium-userland/appium-flutter-driver/issues/461. Please let me know if you need any info. Thanks!

**Comment by pothurajtharun** [comment]
@KazuCocoa  I created a new ticket with full error stack trace. Hers is the ticket https://github.com/appium-userland/appium-flutter-driver/issues/462 . Please let me know if you need any info. Thanks!
