### ISSUE TITLE
Cam we implement flutter automation using Page Object Model/Page Factory ?

### ISSUE THREAD

**Issue by hattersharath** [truongsinh/appium-flutter-driver#33]

**Comment by shibupanda** [comment]
@hattersharath Yes you can implement. Use the finder and Action function for flutter App.

**Comment by ahashmi24** [comment]
@shibupanda 
Does flutter finder expect to throw an error when FlutterElements are not present on the screen?

In the current situation, it is not throwing any error.

**Comment by hattersharath** [comment]
@shibupanda 

@findby support only 8 locators, where I dont see byValueKey. So could you please give me an example of it

Thank you

**Comment by truongsinh** [comment]
`byValueKey` should be supported. You can see the readme on the homepage, or directly at https://github.com/truongsinh/appium-flutter-driver/blob/master/example/nodejs/src/index.js#L36

Feel free to re-open if you need more info.
