### ISSUE TITLE
Publish with updated dependencies?

### ISSUE THREAD

**Issue by imurchie** [truongsinh/appium-flutter-driver#34]
The dependencies are updated but the published version has older ones still. It would be nice to be more easily able to test with the latest working versions of things.

**Comment by truongsinh** [comment]
For the next update, we will bring the version to the same number. When we do so, we will close this issue.

**Comment by truongsinh** [comment]
with commit 3d45cc8df092f83335e760c6fa96cf0d3dd7b444, both driver and finder (nodejs) is not at `0.0.21`
