### ISSUE TITLE
Sendkeys throwing 	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:90)

### ISSUE THREAD

**Issue by hattersharath** [truongsinh/appium-flutter-driver#38]
When I am sending keys to text edit field, I'm getting below exception

java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:90).

This is the line - 
find.byValueKey("searchTextEdit").sendKeys("dress");

**Comment by ahashmi24** [comment]
Hi @hattersharath 
you can use below code snippet instead of sendKeys

MobileElement element = find.byValueKey("searchTextEdit");
element.click();
driver.executeScript("flutter:enterText", "dress");

**Comment by hattersharath** [comment]
Thank you @ahashmi24 
It is working.
