### ISSUE TITLE
Issue while clicking element 

### ISSUE THREAD

**Issue by shibupanda** [truongsinh/appium-flutter-driver#4]
HI, @truongsinh I am getting some error while executing the example(await driver.elementClick(buttonFinder);) script could you please guide me where is the error so that I can also try to contribute some keyword here. 

https://gist.github.com/shibupanda/0691c26c738260da4b6b21e17d15ba10

**Comment by truongsinh** [comment]
I just fix this problem, which was about base64 encoding unsafe for URL, in latest version, `0.0.12`.
