### ISSUE TITLE
Touch actions is giving error -The method touchAction() is undefined for the type AppiumDriver<MobileElement>

### ISSUE THREAD

**Issue by hattersharath** [truongsinh/appium-flutter-driver#42]
driver.touchAction({action: 'tap', element: {elementId: buttonFinder}})

- The method touchAction() is undefined for the type 
	 AppiumDriver<MobileElement>

**Comment by truongsinh** [comment]
@hattersharath which version of the driver and finder are you using?

**Comment by hattersharath** [comment]
Hey @truongsinh, I'm using below versions - 
appium driver version -1.15.0-beta.0
appium-flutter-finder version - 0.0.3

Thank you

**Comment by shibupanda** [comment]
@hattersharath 
Could you please try the latest appium-flutter-driver ---> v0.0.20 and
appium-flutter-finder version - 0.0.4

Please let us know if this help.

**Comment by hattersharath** [comment]
@shibupanda 
I have updated appium-flutter-driver ---> v0.0.20 
But if I update my dependency to
<dependency>
			<groupId>pro.truongsinh</groupId>
			<artifactId>appium-flutter-finder</artifactId>
			<version>0.0.4</version>
		</dependency>

I get error - [WARNING] The POM for pro.truongsinh:appium-flutter-finder:jar:0.0.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by hattersharath** [comment]
@shibupanda could you please provide a link for the 0.0.4 jar.

Thank you

**Comment by shibupanda** [comment]
@hattersharath Please download the complete repository.zip from releases section

**Comment by hattersharath** [comment]
@shibupanda 
Thank you

**Comment by shibupanda** [comment]
@hattersharath Is this working now?

**Comment by hattersharath** [comment]
@shibupanda yet to check, will check it and let you know.

**Comment by shibupanda** [comment]
Closing the issue due to inactivity. Please feel free to reopen.
