### ISSUE TITLE
Unable to  clear a Textfield with Flutterfinder

### ISSUE THREAD

**Issue by pmootyen** [truongsinh/appium-flutter-driver#47]
Hi  
I am trying to clear several text fields with  Appium Flutter but there is no available option.

Except to possibly send a null value with sendkeys please can this be targeted in a fix.

**Comment by shibupanda** [comment]
@pmootyen Till now there is no API in flutter driver to clear the text box.
It's good to hear that passing null value is clearing the Text field.

I am going to raise this request in Flutter Community.

**Comment by truongsinh** [comment]
@pmootyen @shibupanda do you think of sth like this http://appium.io/docs/en/commands/element/actions/clear/ ?

**Comment by shibupanda** [comment]
Yes @truongsinh. Let me reverify it if possible I can send you the pull request today.
