### ISSUE TITLE
appium-flutter-finder needs to publish in npm

### ISSUE THREAD

**Issue by shibupanda** [truongsinh/appium-flutter-driver#5]
HI, @truongsinh appium-flutter-finder needs to publish in npm I guess because still getting an error due to that I guess. I tried to modify but there is no luck.

https://gist.github.com/shibupanda/7fc5cbe06f6c6454bf34b6992e6f033e

**Comment by truongsinh** [comment]
ah true, i forgot to publish NPM :D

**Comment by truongsinh** [comment]
done, please check if we can close this issue.

**Comment by shibupanda** [comment]
No the same error while clicking the element. Are you able to execute all the steps?
Please let me know if I am doing anything wrong.

**Comment by truongsinh** [comment]
did you fork https://github.com/truongsinh/appium-flutter-driver locally and run `npm install` inside `example` dir? could you send the result of `npm list` in that dir? And also the new log from `appium`?

**Comment by shibupanda** [comment]
My fault missed npm install after pull new code. It's working now.

**Comment by truongsinh** [comment]
thanks, let me know if you have any problem, or any feature request.
