### ISSUE TITLE
running tests on native elements in flutter appium driver.

### ISSUE THREAD

**Issue by pradarttana-sharechat** [truongsinh/appium-flutter-driver#53]
Appium version: 1.15.0-beta.0
Device: iOS Simulator
App: Flutter app included plugin (enableFlutterDriverExtension())
language: java

the app consist of some screen which are "flutter" say (login) and some screens are native. say "camera" 
I am able to run the tests using appium flutter driver on the flutter screen.
once I am on the native screen I am switching the context 

`driver.context("NATIVE_APP");`

then using normal appium script,  I am trying to do actions on native elements. 

`public MobileElement <element_name> = (MobileElement) driver.findElement(By.xpath("<xpath_of_element>"));`

 `wait.until(ExpectedConditions.visibilityOf(element_name));`
 `element_name.click();`

while running the script
it is throwing 
`java.lang.NullPointerException` on populating the mobile element on this line.. 

``public MobileElement <element_name> = (MobileElement) driver.findElement(By.xpath("<xpath_of_element>"));``

any help regading this.
@truongsinh @shibupanda

**Comment by truongsinh** [comment]
Frankly, without a piece of code of app-under-test (AUT), it's quite difficult for us to re-produce the crash. Can you try some of the suggestion below:
- upgrade to appium `1.16.0`
- provide more detail for the exception (e.g. is the null pointer exception on the `By` object or `driver` object, or possible loner stack stace)?

**Comment by pradarttana-sharechat** [comment]
@shibupanda . is this not implemented. I found an open issue https://github.com/flutter/flutter/issues/36259

**Comment by truongsinh** [comment]
Yeah I opened that issue awhile ago, but I don't think it's the cause in this case, because `driver.context("NATIVE_APP");` is supposed to help you with the native screen

**Comment by shibupanda** [comment]
@pradarttana-sharechat and @truongsinh 
"NullPointerException" is something if you are passing something null as an argument or you are getting null value as a response.

@pradarttana-sharechat 
Could you please share the complete logs as well using gist.

**Comment by pradarttana-sharechat** [comment]
yes, I got it. I made a mistake on my part.
