### ISSUE TITLE
Getting 'No gulpfile' found exception when installing appium dependencies.

### ISSUE THREAD

**Issue by ahashmi24** [truongsinh/appium-flutter-driver#54]
**Steps:**
**Installing patch version from:** npm i -g appium-flutter-driver https://github.com/truongsinh/appium.git#patch-1
**Go to appium folder:** hitting command npm install

**Getting below issue:**

Ahmers-MacBook-Pro:appium vikasvipul$ npm install
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> fsevents@1.2.11 install /usr/local/lib/node_modules/appium/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> pre-commit@1.2.2 install /usr/local/lib/node_modules/appium/node_modules/pre-commit
> node install.js

> wd@1.12.1 install /usr/local/lib/node_modules/appium/node_modules/wd
> node scripts/build-browser-scripts

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/appium/node_modules/spawn-sync
> node postinstall

> appium@1.15.0-beta.0 prepare /usr/local/lib/node_modules/appium
> gulp prepublish

[20:05:10] No gulpfile found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium@1.15.0-beta.0 prepare: `gulp prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium@1.15.0-beta.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vikasvipul/.npm/_logs/2020-02-10T14_35_10_885Z-debug.log

**Comment by shibupanda** [comment]
@ahashmi24 I don't think now patch version is required as Appium 1.16.0 support Appium flutter driver beta. 

Please update the flutter driver dependency to latest in package.json and do npm install.

**Comment by ahashmi24** [comment]
@shibupanda 
I tried the same what suggested. However, I am still getting same issue:

> appium@1.16.0 prepare /usr/local/lib/node_modules/appium
> gulp prepublish

[22:50:23] No gulpfile found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium@1.16.0 prepare: `gulp prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium@1.16.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

is it possible to push these fixes to appium beta?

**Comment by shibupanda** [comment]
@ahashmi24 are you able to start Appium 1.16.0 successfully even after getting above error. If yes then please try to execute the script and check once.

**Comment by ahashmi24** [comment]
@shibupanda 
I have updated appium-flutter-driver version manual by below command:
npm install -g appium-flutter-driver

Now, it is showing :

Ahmers-MacBook-Pro:~ vikasvipul$ npm ls -g appium-flutter-driver
/usr/local/lib
├─┬ appium@1.16.0
│ └── appium-flutter-driver@0.0.21 
└── appium-flutter-driver@0.0.21 

However, the "waitFor" flutter command behaves as previously.

**Comment by shibupanda** [comment]
@ahashmi24 could you please share complete Appium logs using gist.

**Comment by ahashmi24** [comment]
@shibupanda 
Please find the gist for the same:
https://gist.github.com/ahashmi24/788098b5ee41bb8cba9e3640c2fc0f91

Code snippet:
driver.context("FLUTTER");
FlutterElement buttonToOpenCalendar = find.byValueKey("button"); // intentionally I used incorrect value key
driver.executeScript("flutter:waitFor", buttonToOpenCalendar);

**Comment by shibupanda** [comment]
@ahashmi24 looks like it's a existing driver not the latest one. Please install correctly.
One suggestion it may work for you. Please delete the existing appium-flutter-driver from node modules and please install the latest driver in the same node modules directory without -g.

@truongsinh any idea when the flutter driver latest version will come up with appium bundle.

**Comment by truongsinh** [comment]
@shibupanda @ahashmi24 
Yes, firstly, `1.16.0` of appium already include `appium-flutter-driver`, so we no longer need the patch version. I will update README.
<img width="911" alt="Screen Shot 2020-02-11 at 14 01 41" src="https://user-images.githubusercontent.com/358585/74216438-0db70800-4cd7-11ea-8467-5a14ea82d0ee.png">
Can you try remove and re-install appium? This seems to be the error from `appium` package.

**Comment by ahashmi24** [comment]
@shibupanda @truongsinh 
I have tried installing appium beta version (npm install -g appium@beta) and could see the latest appium-flutter-driver version which is coming with appium beta bundle.

Ahmers-MacBook-Pro:~ vikasvipul$ appium -v
1.16.0-beta.3
Ahmers-MacBook-Pro:~ vikasvipul$ npm ls -g appium-flutter-driver
/usr/local/lib
├─┬ appium@1.16.0-beta.3
│ └── appium-flutter-driver@0.0.21 
└── appium-flutter-driver@0.0.21 

However, waitFor command still stuck when an element is not present on the screen or passing an invalid locator.

Appium logs:
https://gist.github.com/ahashmi24/d81ead9e8938324e2cca3c943059540f

**Comment by shibupanda** [comment]
Hi @ahashmi24 
We have already updated in README and in nodejs example that from now onward there is one more argument need to pass in wait commands. Needs to be added in other examples as well.

Could you please try below code for java.
driver.executeScript("flutter:waitFor", find.text("I can enter text"), new HashMap<String, Object>() {{
      put("durationMilliseconds", 100);
 }});

**Comment by ahashmi24** [comment]
@shibupanda 
It's throwing an exception "**org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: durationMilliseconds is not a valid options (WARNING: The server did not provide any stacktrace information)**"

### After adding below code snippet:
 driver.executeScript("flutter:waitFor", find.byValueKey("button"), new HashMap<String, Object>(){{
				 put("durationMilliseconds", 100);}});

Appium logs:
https://gist.github.com/ahashmi24/802d87814ec2e41768136726029741db

**Comment by ahashmi24** [comment]
@shibupanda 

I got it, below syntax is working fine for me:

driver.executeScript("flutter:waitFor", find.byValueKey("button"), 1);

Hence, closing this issue.
