### ISSUE TITLE
wait.untill is not working in ios-native elements after driver.context("NATIVE_APP");

### ISSUE THREAD

**Issue by pradarttana-sharechat** [truongsinh/appium-flutter-driver#57]
platform:-
appium: 1.16.0
finder: 0.0.4

issue:-
`      LoginPage loginPage = new LoginPage(driver);

        loginPage.login();

        HomePage homePage= new HomePage(driver);

        homePage.navigateToUpload();

        driver.context("NATIVE_APP");

        ComposeFileUploadScreen composeFileUploadScreen = new ComposeFileUploadScreen(driver);
        wait.until(ExpectedConditions.elementToBeClickable(composeFileUploadScreen.getGifIcon()));

      //  Thread.sleep(5000);

        composeFileUploadScreen.getGifIcon().click();

        System.out.println("getting test"+composeFileUploadScreen.getGifIcon().getText());
`

the test failing at wait.until line. 

the appium log  is:-https://gist.github.com/pradarttana-sharechat/d3062a199466c376857ca384af331261

if I am removing the `wait.until` line and give a manual wait using `Thread.sleep(5000);` i am able to click on that element

any help?

**Comment by pradarttana-sharechat** [comment]
@truongsinh @shibupanda any update?

**Comment by shibupanda** [comment]
@pradarttana-sharechat please use Flutter methods like waitFor or waitForAbsent in Flutter driver.

**Comment by pradarttana-sharechat** [comment]
in leave for few days. will try that

**Comment by shibupanda** [comment]
@pradarttana-sharechat 
Could you please update on the same.
