### ISSUE TITLE
Unable to use flutter in appium with python client

### ISSUE THREAD

**Issue by CarrotXin** [truongsinh/appium-flutter-driver#64]
Hi:
        After install appium-flutter-driver and refrenced with the example.py
        capabilities = {
                "platformName": "android",
                "deviceName": "Samsung Galaxy S7_2",
                "platformVersion": "7.1.1",
                "automationName": "flutter",
                "app": "/Users/yjf/opt/anaconda3/envs/ef_mobile_automation/mobile/interfaces/client_ui/apps/engage-juno-uat-debug-2.1.0-flutter.apk"
}
                driver = Remote('http://localhost:4723/wd/hub', capabilities)

After running the code, errors are listed as following:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'flutter' and platformName 'android'. Please check your desired capabilities.
Could you give some suggestion? Thanks a lot.

**Comment by Rodaxfck** [comment]
Hello,

Maybe you don't have [appium](https://github.com/appium/appium/releases) 1.16.0 (beta support for Flutter) installed

**Comment by CarrotXin** [comment]
@Rodaxfck ,
Hello, 
(mobile_automation) yujianfengdeMacBook-Pro:appium yjf$ appium -v
1.16.0-beta.2

The correct appium verison should be?Thanks a lot.
