### ISSUE TITLE
Python using flutter driver

### ISSUE THREAD

**Issue by CarrotXin** [truongsinh/appium-flutter-driver#65]
Hi:
    Referenced with the example code under python demo dir,  it can't work well.
    I have some questions:
    (1)  Is the flutter-appium-finder newest code?
    (2)  Can this package work well with python3.7?
    

Something wrong with base64 encode in _serialize with python3.7
def _serialize(self, finder_dict):
        return base64.b64encode(json.dumps(finder_dict))

**Comment by CarrotXin** [comment]
Hi:
    Another question:
    capabilities = {
  "platformName": "android",
  "deviceName": "Samsung Galaxy S7_2",
  "platformVersion": "7.1.1",
  "automationName": "flutter",
  "autoGrantPermissions": True,
  "adbExecTimeout": 60000,
  "newCommandTimeout": 7200,
  "appPackage": "com.xxx.xxx.xxx.xxx",
  "appActivity": "com.xxx.xxx.xxx.xxx.xxx.activity.xxx",
  "app": "/Users/yjf/opt/anaconda3/envs/ef_mobile_automation/mobile/interfaces/client_ui/apps/engage-juno-uat-debug-2.1.0-flutter.apk"
}

driver = Remote('http://localhost:4723/wd/hub', capabilities)
activity_name = 'flutter.plugins.EngageFlutterActivity'
activity_loaded = driver.wait_activity(
            activity_name, timeout=timeout, interval=interval)
finder = FlutterFinder()
test = 'Try something'
text_finder = finder.by_text(test)
element = FlutterElement(driver, text_finder)
print(element.text)
text_finder.click()

After run code above, session seems always to be terminated automatically, errors:
[debug] [MJSONWP (04f95222)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [MJSONWP (04f95222)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:252:15)
[debug] [MJSONWP (04f95222)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:432:15
[debug] [MJSONWP (04f95222)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP (04f95222)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [MJSONWP (04f95222)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [MJSONWP (04f95222)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP (04f95222)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [MJSONWP (04f95222)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [MJSONWP (04f95222)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [MJSONWP (04f95222)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [MJSONWP (04f95222)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [MJSONWP (04f95222)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [MJSONWP (04f95222)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP (04f95222)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [MJSONWP (04f95222)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [MJSONWP (04f95222)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [MJSONWP (04f95222)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [MJSONWP (04f95222)]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:110:7)
[debug] [MJSONWP (04f95222)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP (04f95222)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [MJSONWP (04f95222)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [MJSONWP (04f95222)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)

Can someone tell me the root cause of this error  and how can I resolve it? Thanks a lot.

**Comment by Rodaxfck** [comment]
Hello,

For the first question, I also in my case experienced an issue with python 3.7 an this function...

I fixed it myself by editing the function : 

def _serialize(self, finder_dict):
        return base64.b64encode(bytes(json.dumps(finder_dict).encode('utf-8'))).decode('utf-8')

These is for sure a better way to fix this because I don't know python, but it works for me!

**Comment by CarrotXin** [comment]
Hello Rodaxfck :

        Do you use python client to send_key and have some examples? Thanks.

**Comment by CarrotXin** [comment]
Hi:
     After reading https://github.com/truongsinh/appium-flutter-driver , I want to ask:
    If I use enterText, the url of this operation should be?
    With python client, requests are send as following:
    /session/$sessionId/appium/element/$id/replace_value
   Where can I get all urls supported with appium-flutter-driver?

**Comment by Rodaxfck** [comment]
> 
> 
> Hello Rodaxfck :
> 
> ```
>     Do you use python client to send_key and have some examples? Thanks.
> ```

In your case sendKeys should work (http://appium.io/docs/en/commands/element/actions/send-keys/)

driver = Remote('http://localhost:4723/wd/hub', capabilities)
finder = FlutterFinder()
test = 'Try something'
text_finder = finder.by_text(test)
element = FlutterElement(driver, text_finder)
element.send_keys(text)

**Comment by CarrotXin** [comment]
Hello Rodaxfck:
       Appreciated!
       I used the '/session/$sessionId/element/$id/value' and it seems to work (no errors). 
       But no response return and after long time, errors are raised:
       Traceback (most recent call last):
  File "/Users/yjf/opt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/yjf/opt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/yjf/opt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/yjf/opt/anaconda3/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/Users/yjf/opt/anaconda3/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Users/yjf/opt/anaconda3/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

       In simulator, I can't input the string with keyboard after developer enableFlutterDriverExtension() 
       before runApp. 
       How can I work around it? Thanks.
