### ISSUE TITLE
Error: Failed to create session. read ECONNRESET

### ISSUE THREAD

**Issue by YahyaQandel** [truongsinh/appium-flutter-driver#77]
Appium version : 1.17.0
Application : flutter app
test runner : mocha

```
opts = {
      host: 'localhost',
      logLevel: 'info',
      port: 4723,
      path: "/wd/hub", 
      capabilities: {
        platformName: 'Android',
        deviceName: "Pixel_ASHTAR_HPEmulator",
        app: resolve("__tests__/config/test-app.apk"),
        automationName: 'Flutter',
        platformVersion: "9.0",
      }
    };
```

when i change **automationName** from **Flutter** to **UIAutomator2** it works, i don't know how it should work I have installed appium-flutter-driver but i don't know how to use it .
i'm just starting appium in another terminal screen as i was using it before .

Appium logs:

```
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1588531531800 (20:45:31 GMT+0200 (Eastern European Standard Time))
[debug] [W3C] Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[debug] [W3C]     at Object.exports.processLogToGetobservatory (/Users/Yahya/WebstormProjects/Nis-e2e/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:128:9)
[debug] [W3C]     at Object.exports.getObservatoryWsUri (/Users/Yahya/WebstormProjects/Nis-e2e/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/android.ts:34:21)
[debug] [W3C]     at Object.exports.startAndroidSession (/Users/Yahya/WebstormProjects/Nis-e2e/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/android.ts:25:28)
[debug] [W3C]     at FlutterDriver.exports.createSession (/Users/Yahya/WebstormProjects/Nis-e2e/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:18:47)
[debug] [W3C]     at AppiumDriver.createSession (/Users/Yahya/WebstormProjects/Nis-e2e/node_modules/appium/lib/appium.js:358:35)
[debug] [W3C] Destroying socket connection
```

**Comment by shibupanda** [comment]
@YahyaQandel 
Could you please send the complete logs using gist.
For flutter application you can only use automationName as Flutter.

**Comment by YahyaQandel** [comment]
> @YahyaQandel
> Could you please send the complete logs using gist.

Here it is
https://gist.github.com/YahyaQandel/029f2bf5a9a2d572b5acb0eda79df344

**Comment by shibupanda** [comment]
hi @YahyaQandel which version of appium it is? As the logs are not complete I am not able to see appium server version. Please send me the complete logs started from Appium server.

**Comment by shibupanda** [comment]
Ok I will check from my side.
> I have installed appium-flutter-driver but i don't know how to use it .

No need to install it separately.

**Comment by YahyaQandel** [comment]
Thanks great, thanks for your collaboration

**Comment by YahyaQandel** [comment]
Is there a toy project for appium testing flutter app with appium-flutter-driver ?

**Comment by YahyaQandel** [comment]
Any solution ?

**Comment by shibupanda** [comment]
@YahyaQandel I will validate it in this weekend.
Mean time please uninstall and install appium once and don't install appium-flutter-driver separately as it comes as a bundle with appium,

You can refer https://github.com/truongsinh/appium-flutter-driver/tree/master/example.

**Comment by shibupanda** [comment]
@YahyaQandel 
Please check https://github.com/truongsinh/appium-flutter-driver/issues/82

Closing due to duplicate issue.
