### ISSUE TITLE
Getting unknow locator using Appium Flutter Driver 

### ISSUE THREAD

**Issue by Vishu0078** [truongsinh/appium-flutter-driver#98]
Tried to automated Flutter application using Appium Flutter Driver, resolved all dependencies but when run it then after lunching application, driver is throwing below error.

org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html

Locators/Byvalues are correct as it is working in DART test automation.

FlutterElement e = find.byValueKey("emailTxt");
e.sendKeys("test@gmail.com");

OR

MobileElement e = find.byValueKey("emailTxt");
e.sendKeys("test@gmail.com");

showing due to unknow locator test get failed.

import pro.truongsinh.appium_flutter.FlutterFinder;
import pro.truongsinh.appium_flutter.finder.FlutterElement;

Used jar ----kotlin-finder-0.0.4

**Comment by baovu2512** [comment]
do you forgot automationName = Flutter ?

**Comment by sahanaprasad** [comment]
How did you resolve the dependency for appium_flutter finder in maven?
Kindly let me know. I'm having the same issue.

**Comment by baovu2512** [comment]
> How did you resolve the dependency for appium_flutter finder in maven?
> Kindly let me know. I'm having the same issue.
What maven issue you are facing?

**Comment by sahanaprasad** [comment]
This dependency is not found
<dependency>
			<groupId>pro.truongsinh</groupId>
			<artifactId>appi um-flutter-finder</artifactId>
			<version>0.0.4</version>
		</dependency>

**Comment by baovu2512** [comment]
You can check this. https://github.com/truongsinh/appium-flutter-driver/issues/29

**Comment by sahanaprasad** [comment]
I got this error while importing jar file through maven command.
 standalone-pom: Error parsing POM /Users/<username>/Downloads/repository/pro/truongsinh/appium-flutter-finder/0.0.4/appium-flutter-finder-0.0.4.jar

**Comment by baovu2512** [comment]
You can move pro/truongsinh/ to maven home. Then on your project. Run mvn install

**Comment by sahanaprasad** [comment]
When i tried mvn install after moving  pro/truongsinh/ i get the following error. @baovu2512 

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.138 s
[INFO] Finished at: 2020-10-05T11:00:28+05:30
[INFO] Final Memory: 6M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/sahanaprasad/development/appium-flutter-driver). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
